// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPAnamnese.ApiService.Data;

#nullable disable

namespace SPAnamnese.ApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617171931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbanamnese", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AntAlergias")
                        .HasColumnType("text");

                    b.Property<string>("AntCirurgiasInternacoes")
                        .HasColumnType("text");

                    b.Property<string>("AntDoencasPrevias")
                        .HasColumnType("text");

                    b.Property<string>("AntGestacaoPartos")
                        .HasColumnType("text");

                    b.Property<string>("AntMedicamentos")
                        .HasColumnType("text");

                    b.Property<string>("AntVacinas")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DataAtualizacao"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("ExpectativaPaciente")
                        .HasColumnType("text");

                    b.Property<string>("FamCancer")
                        .HasColumnType("text");

                    b.Property<string>("FamCardiopatiasAvc")
                        .HasColumnType("text");

                    b.Property<string>("FamDoencasCronicas")
                        .HasColumnType("text");

                    b.Property<string>("FamDoencasHereditarias")
                        .HasColumnType("text");

                    b.Property<string>("FamTranstornosMentais")
                        .HasColumnType("text");

                    b.Property<string>("HabAlimentacaoSonoHidratacao")
                        .HasColumnType("text");

                    b.Property<string>("HabAtividadeFisica")
                        .HasColumnType("text");

                    b.Property<string>("HabEstressePsicossocial")
                        .HasColumnType("text");

                    b.Property<string>("HabSubstancias")
                        .HasColumnType("text");

                    b.Property<string>("HabTrabalhoPostura")
                        .HasColumnType("text");

                    b.Property<string>("HmaEvolucao")
                        .HasColumnType("text");

                    b.Property<string>("HmaImpactoRotina")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HmaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HmaLocalizacao")
                        .HasColumnType("text");

                    b.Property<string>("HmaMelhoraPiora")
                        .HasColumnType("text");

                    b.Property<string>("HmaSintomasAssociados")
                        .HasColumnType("text");

                    b.Property<string>("HmaTratamentosFeitos")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("PlanoDataRetorno")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlanoOrientacoesIniciais")
                        .HasColumnType("text");

                    b.Property<string>("PlanoProximosPassos")
                        .HasColumnType("text");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("int(11)");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("RevCardiovascular")
                        .HasColumnType("text");

                    b.Property<string>("RevDermatologico")
                        .HasColumnType("text");

                    b.Property<string>("RevGastrointestinal")
                        .HasColumnType("text");

                    b.Property<string>("RevGeniturinario")
                        .HasColumnType("text");

                    b.Property<string>("RevNeurologico")
                        .HasColumnType("text");

                    b.Property<string>("RevOsteoarticular")
                        .HasColumnType("text");

                    b.Property<string>("RevOutros")
                        .HasColumnType("text");

                    b.Property<string>("RevRespiratorio")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PacienteId" }, "idx_paciente");

                    b.HasIndex(new[] { "ProfissionalId" }, "idx_profissional");

                    b.ToTable("tbanamnese");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbanexo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATENDIMENTOID")
                        .HasColumnType("int(11)");

                    b.Property<string>("CAMINHO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DATACADASTRO")
                        .HasColumnType("datetime");

                    b.Property<string>("NOMEARQUIVO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbanexo");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbatendimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATAATENDIMENTO")
                        .HasColumnType("datetime");

                    b.Property<string>("OBSERVACOES")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PACIENTEID")
                        .HasColumnType("int(11)");

                    b.Property<int>("PROFISSIONALID")
                        .HasColumnType("int(11)");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbatendimento");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbformulario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VERSAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbformulario");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbpaciente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateOnly>("DATANASCIMENTO")
                        .HasColumnType("date");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ENDERECO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESPONSAVELLEGAL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SEXO")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbpaciente");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbperguntum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FORMULARIOID")
                        .HasColumnType("int(11)");

                    b.Property<bool>("OBRIGATORIA")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ORDEM")
                        .HasColumnType("int(11)");

                    b.Property<string>("TEXTO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TIPOCAMPO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbpergunta");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbprofissional", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PERFIL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbprofissional");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbrespostum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATENDIMENTOID")
                        .HasColumnType("int(11)");

                    b.Property<int>("PERGUNTAID")
                        .HasColumnType("int(11)");

                    b.Property<string>("VALOR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID")
                        .HasName("PRIMARY");

                    b.ToTable("tbresposta");
                });

            modelBuilder.Entity("SPAnamnese.ApiService.Models.tbanamnese", b =>
                {
                    b.HasOne("SPAnamnese.ApiService.Models.tbpaciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPAnamnese.ApiService.Models.tbprofissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });
#pragma warning restore 612, 618
        }
    }
}
